{% set version = "4.9.0" %}

package:
  name: pexpect
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pexpect/pexpect-{{ version }}.tar.gz
  sha256: ee7d41123f3c9911050ea2c2dac107568dc43b2d3b0c7557a33212c398ead30f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ptyprocess >=0.5

test:
  imports:
    - pexpect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pexpect.readthedocs.io/
  summary: Pexpect allows easy control of interactive console applications.
  license: ISC
  license_file: LICENSE
  dev_url: https://github.com/pexpect/pexpect

extra:
  recipe-maintainers:
    - jquast
    - pelson
    - takluyver
    - ocefpaf
